name: container_server_example
publish_to: none # not intended for publication to pub.dev

environment:
  sdk: ^3.0.0

dependencies:
  shelf: ^1.2.0
  shelf_router: ^1.0.0
  shelf_static: ^1.0.0
  args: 2.4.2
  drift: 2.8.2
  path: 1.8.3
  sqlite3: 1.11.2
  crypto: ^3.0.3

dev_dependencies:
  http: ^0.13.0
  lints: ^2.0.0
  test: ^1.15.0
  test_process: ^2.0.0
  drift_dev: 2.8.2
  build_runner: 2.4.5
